Repository microsoft/azuredatastudio, pull requests merged in 2019-10, with the labels that each got.

#7457 Disable hw accl
  scripts/test-extensions-unit.bat
  scripts/test-extensions-unit.sh
  src/main.js
Labels: Ready to Merge

#7486 Disable one test and add a new utility function
  extensions/integration-tests/src/objectExplorer.test.ts
  extensions/integration-tests/src/utils.ts
Labels: Ready to Merge

#6699 Fixed issue where task icons got hidden if text was too long
  src/sql/workbench/parts/tasks/browser/media/tasksPanel.css
Labels: Stale PR

#7203 allows zone.js to cleanup error stacktraces
  src/sql/setup.js
  test/electron/renderer.js
Labels: Ready to Merge

#6891 Fix #6884 Notebook: Notebook ModelReady Event can be Fired Multiple Times
  src/sql/workbench/parts/notebook/browser/models/notebookInput.ts
Labels: Stale PR

#7169 Some cleanup on queryEditorService
  src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
Labels: Stale PR

#7525 Flat file import version bump
  extensions/import/config.json
Labels: Ready to Merge

#7550 Add chmod +x to all the scripts
  scripts/test-extensions-unit-unstable.bat
  scripts/test-extensions-unit-unstable.sh
  scripts/test-extensions-unit.bat
  scripts/test-extensions-unit.sh
  scripts/test-integration.bat
Labels: Ready to Merge

#7575 Enable prod mode if the service is built
  src/sql/platform/bootstrap/browser/bootstrapService.ts
Labels: Ready to Merge

#7650 add lgtm file
  lgtm.yml
Labels: Ready to Merge

#7727 Add name and change severity
  .lgtm/javascript-queries/promises.ql
Labels: Ready to Merge

#7748 XML output is truncated
  extensions/mssql/package.json
  extensions/mssql/package.nls.json
  src/sql/azdata.d.ts
  src/sql/workbench/parts/query/browser/queryActions.ts
Labels: Ready to Merge

#7617 Test run list proposal
  build/gulpfile.hygiene.js
  build/testSetup.js
  build/testSetup.ts
  runlist.json
Labels: Impact: DRI

#7300 Strict null on some query and connection
  src/sql/azdata.d.ts
  src/sql/platform/common/pathUtilities.ts
  src/sql/platform/connection/common/connectionConfig.ts
  src/sql/platform/connection/common/connectionProfile.ts
  src/sql/platform/connection/common/connectionProfileGroup.ts
  src/sql/platform/connection/common/connectionStatusManager.ts
  src/sql/platform/connection/common/connectionStore.ts
  src/sql/platform/connection/common/utils.ts
  src/sql/platform/query/common/gridDataProvider.ts
  src/sql/platform/query/common/queryManagement.ts
  src/sql/platform/query/common/queryModel.ts
  src/sql/platform/query/common/queryModelService.ts
  src/sql/platform/query/common/queryRunner.ts
  src/sql/sqlops.d.ts
  src/sql/workbench/api/browser/mainThreadDataProtocol.ts
  src/sql/workbench/parts/editData/browser/editData.component.ts
  src/sql/workbench/parts/grid/common/dataService.ts
  src/sql/workbench/parts/query/common/gridPanelState.ts
  src/sql/workbench/parts/query/common/queryInput.ts
  src/sql/workbench/parts/query/common/queryResultsInput.ts
  src/sql/workbench/parts/query/common/resultSerializer.ts
  src/tsconfig.strictNullChecks.json
Labels: Stale PR

#7874 Add a new unstable test
  extensions/integration-tests/src/notebook.test.ts
Labels: Impact: DRI

#7875 Lets try out this gh-action
  .github/workflows/tslint.yml
Labels: Impact: DRI

#8100 More promise cleanup
  src/sql/platform/connection/browser/connectionManagementService.ts
  src/sql/workbench/api/browser/mainThreadQueryEditor.ts
  src/sql/workbench/browser/modelComponents/editor.component.ts
  src/sql/workbench/browser/scriptingActions.ts
  src/sql/workbench/browser/scriptingUtils.ts
  src/sql/workbench/parts/dashboard/browser/dashboardEditor.ts
  src/sql/workbench/parts/query/browser/queryEditor.ts
  src/sql/workbench/services/connection/browser/cmsConnectionController.ts
  src/sql/workbench/services/connection/browser/connectionController.ts
  src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
  src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
Labels: Ready to Merge
