Repository microsoft/azuredatastudio, pull requests merged in 2020-04, with the labels that each got.

#9826 We can't authenticate to every subscription
  extensions/azurecore/src/account-provider/auths/azureAuth.ts
  extensions/azurecore/src/azureResource/tree/accountTreeNode.ts
Labels: Ready to Merge

#9954 port request for PR 9951
  extensions/mssql/package.json
  src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.contribution.ts
Labels: Approved, Port Request

#9969 port request for PR #9966
  src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.css
Labels: Port Request

#9978 Add Open Notebook Folder functionality to Books viewlet. (#9939)
  extensions/notebook/package.json
  extensions/notebook/package.nls.json
  extensions/notebook/resources/dark/open_folder_inverse.svg
  extensions/notebook/resources/light/open_folder.svg
  extensions/notebook/src/book/bookModel.ts
  extensions/notebook/src/book/bookTreeItem.ts
  extensions/notebook/src/book/bookTreeView.ts
  extensions/notebook/src/common/localizedConstants.ts
  extensions/notebook/src/extension.ts
  extensions/notebook/src/test/book/book.test.ts
  extensions/notebook/src/test/book/bookTrustManager.test.ts
  src/sql/workbench/contrib/notebook/browser/notebook.component.ts
Labels: Approved, Port Request

#9988 Only show Create Insight button in Query Editor charts. (#9973)
  src/sql/workbench/contrib/charts/browser/chartView.ts
  src/sql/workbench/contrib/charts/test/browser/chartView.test.ts
Labels: Approved, Port Request

#9990 Added Notebook telemetry for livesite notebooks (#9948)
  src/sql/platform/telemetry/common/telemetryKeys.ts
  src/sql/workbench/contrib/notebook/browser/notebook.component.ts
  src/sql/workbench/contrib/notebook/test/electron-browser/notebookEditorModel.test.ts
  src/sql/workbench/contrib/notebook/test/electron-browser/notebookFindModel.test.ts
  src/sql/workbench/contrib/notebook/test/electron-browser/notebookModel.test.ts
  src/sql/workbench/services/notebook/browser/models/notebookModel.ts
Labels: Approved, Port Request

#10006 Fixes #9397 Launch onenote links (#9931)
  src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts
Labels: Approved, Port Request

#10028 Add innoupdater for windows fast update
  build/azure-pipelines/win32/sql-product-build-win32.yml
  build/win32/code.iss
  src/vs/platform/update/common/update.config.contribution.ts
Labels: Port Request

#9993 Allow users to use file based key storage if they have to
  extensions/azurecore/src/account-provider/simpleTokenCache.ts
Labels: Port Request

#9999 Put cloud shell behind preview flag (#9995)
  extensions/azurecore/src/azureResource/commands.ts
Labels: Port Request

#10000 Listen on localhost only (#9997)
  extensions/azurecore/src/account-provider/utils/simpleWebServer.ts
Labels: Port Request

#10007 Fix for edit data table size #9967
  src/sql/workbench/contrib/editData/browser/media/editData.css
Labels: Port Request

#10030 Merge from vscode ff915844119ce9485abfe8aa9076ec76b5300ddd
  build/gulpfile.vscode.js
  extensions/git/package.json
  extensions/git/src/git.ts
  src/vs/base/common/fuzzyScorer.ts
  src/vs/base/parts/quickinput/browser/quickInput.ts
  src/vs/base/parts/quickinput/browser/quickInputList.ts
  src/vs/code/electron-main/app.ts
  src/vs/editor/contrib/quickAccess/gotoSymbolQuickAccess.ts
  src/vs/workbench/browser/parts/compositeBarActions.ts
  src/vs/workbench/contrib/search/browser/anythingQuickAccess.ts
  src/vs/workbench/contrib/search/browser/symbolsQuickAccess.ts
  src/vs/workbench/electron-browser/desktop.contribution.ts
  src/vs/workbench/services/integrity/node/integrityService.ts
  src/vs/workbench/services/search/common/searchService.ts
Labels: Port Request

#10010 Fix duplicating list on extension pack (#9992) (#10003)
  src/sql/workbench/contrib/welcome/page/browser/welcomePage.css
  src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
Labels: Port Request

#10033 Welcome responsive container (#9946) (#9870)
  src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
  src/sql/workbench/contrib/welcome/page/browser/welcomePage.css
  src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
Labels: Port Request

#10031 Bring back hover buttons for adding cells (#10012)
  src/sql/workbench/contrib/notebook/browser/notebook.component.html
Labels: Approved, Port Request

#10013 Notebooks: Fix Issue Around Load Error when Tables Have No Rows (#9980)
  src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
Labels: Approved, Port Request

#10046 replaced watch with watchFile (#9873)
  extensions/notebook/src/book/bookTreeView.ts
  extensions/notebook/src/common/utils.ts
  extensions/notebook/tsconfig.json
Labels: Approved, Port Request

#10045 Fix/find context correction (#9949)
  src/sql/workbench/contrib/notebook/browser/notebookEditor.ts
Labels: Approved, Port Request

#10024 UI - Markdown toolbar now behind preview flag
  src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.html
  src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
  src/sql/workbench/contrib/notebook/browser/notebook.component.ts
Labels: Area - Notebooks, UI

#10047 Check conda-forge channel first when installing conda packages. (#10035)
  extensions/notebook/src/jupyter/jupyterServerInstallation.ts
Labels: Approved, Port Request

#10048 Rename/books viewlet sections (#10044)
  extensions/notebook/package.json
  extensions/notebook/package.nls.json
Labels: Approved, Port Request

#10054 fix error when notebook save is cancelled (#10032)
  src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
Labels: Approved, Port Request

#10050 UI - Markdown toolbar now behind preview flag (#10024)
  src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.html
  src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
  src/sql/workbench/contrib/notebook/browser/notebook.component.ts
Labels: Approved, Port Request

#9953 port PR 9937 to release branch
  src/sql/base/browser/ui/panel/media/panel.css
  src/sql/base/browser/ui/panel/panel.component.ts
  src/sql/base/browser/ui/panel/tabHeader.component.ts
Labels: Port Request

#10040 port the dashboard scroll issue to release branch
  src/sql/workbench/contrib/dashboard/browser/containers/dashboardGridContainer.component.ts
  src/sql/workbench/contrib/dashboard/browser/containers/dashboardHomeContainer.component.ts
  src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.html
  src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts
Labels: Port Request

#10070 Fix relative paths on anchor links (#9958)
  src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts
Labels: Port Request

#10074 Notebook UI - Fixes navigation offset (#10067)
  src/sql/workbench/contrib/notebook/browser/notebook.component.ts
Labels: Port Request

#10092 Check treeItem first when building search path in searchJupyterBooks. (#10083)
  extensions/notebook/src/book/bookTreeView.ts
  extensions/notebook/src/common/localizedConstants.ts
Labels: Port Request

#10087 Revert "Create new row upon focus on last row (#9046)" (#10039)
  src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
Labels: Port Request

#10077 Enable file based storage by default (#10061)
  extensions/azurecore/package.json
Labels: Port Request

#10053 Bbrady/release port/fixes video and admin pack images
  src/sql/workbench/contrib/welcome/media/extension_pack_img.svg
  src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
  src/sql/workbench/contrib/welcome/page/browser/welcomePage.css
  src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
Labels: Port Request

#10096 Check for file scheme in linkhandler (#10090)
  src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts
Labels: Port Request

#10099 Put new welcome page behind preview features flag
  src/sql/workbench/contrib/welcome2/gettingStarted/browser/abstractEnablePreviewFeatures.ts
  src/sql/workbench/contrib/welcome2/gettingStarted/browser/enablePreviewFeatures.ts
  src/sql/workbench/contrib/welcome2/gettingStarted/browser/gettingStarted.contribution.ts
  src/sql/workbench/contrib/welcome2/gettingStarted/electron-browser/enablePreviewFeatures.ts
  src/sql/workbench/contrib/welcome2/gettingStarted/electron-browser/gettingStarted.contribution.ts
  src/sql/workbench/contrib/welcome2/page/browser/az_data_welcome_page.ts
  src/vs/workbench/contrib/welcome/page/browser/welcomePage.contribution.ts
  src/vs/workbench/contrib/welcome/page/browser/welcomePage.css
  src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts
Labels: Port Request

#10107 Clear all saved accounts regardless of failure
  src/sql/workbench/services/accountManagement/browser/accountManagementService.ts
Labels: Port Request

#10117 import correct welcome page
  src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts
Labels: Port Request

#10132 Delete deprecated accounts (#10131)
  src/sql/platform/accounts/common/accountStore.ts
  src/sql/platform/accounts/test/common/accountStore.test.ts
Labels: Port Request

#10146 Change the authenticationType (#10139)
  extensions/azurecore/src/azureResource/providers/database/databaseTreeDataProvider.ts
  extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerTreeDataProvider.ts
  extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerTreeDataProvider.ts
  extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerTreeDataProvider.ts
  extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceTreeDataProvider.ts
  extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcTreeDataProvider.ts
Labels: Approved, Port Request

#10150 Set the username (#10149)
  extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerTreeDataProvider.ts
Labels: Port Request

#10219 Add a trailing slash (#10218)
  extensions/azurecore/src/account-provider/providerSettings.ts
Labels: Port Request
