Repository microsoft/azuredatastudio, pull requests merged in 2020-10, with the labels that each got.

#12721 Aasim/release1.23/importfixes
  extensions/import/config.json
  extensions/import/src/wizard/pages/modifyColumnsPage.ts
  extensions/import/src/wizard/pages/summaryPage.ts
Labels: Port Request

#12734 update preview feature notification (#12723)
  src/sql/workbench/contrib/welcome/gettingStarted/browser/abstractEnablePreviewFeatures.ts
Labels: Port Request

#12736 [Port] Fix root group name check (#12660)
  src/sql/platform/connection/common/connectionProfileGroup.ts
Labels: Port Request

#12738 [Port] Add ModelViewEditorOpened event #12597
  extensions/arc/src/ui/components/dashboard.ts
  extensions/arc/src/ui/dashboards/controller/controllerDashboard.ts
  extensions/arc/src/ui/dashboards/miaa/miaaDashboard.ts
  extensions/arc/src/ui/dashboards/postgres/postgresDashboard.ts
  extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboard.ts
  extensions/schema-compare/src/schemaCompareMainWindow.ts
  src/sql/azdata.d.ts
  src/sql/azdata.proposed.d.ts
  src/sql/platform/telemetry/common/telemetryKeys.ts
  src/sql/workbench/api/browser/mainThreadModelViewDialog.ts
  src/sql/workbench/api/common/extHostModelViewDialog.ts
  src/sql/workbench/api/common/sqlExtHost.api.impl.ts
  src/sql/workbench/api/common/sqlExtHost.protocol.ts
  src/sql/workbench/test/electron-browser/api/mainThreadModelViewDialog.test.ts
Labels: Port Request

#12735 [Port] Fix checkbox change event not firing on enter press (#12703)
  src/sql/base/browser/ui/checkbox/checkbox.ts
Labels: Port Request

#12743 updating SqltoolsService Version to Pick DacFx changes
  extensions/mssql/config.json
Labels: Port Request

#12739 [Port] vBump notebooks to get latest CU6 version of book (#12683)
  product.json
Labels: Port Request

#12746 Port ML changes
  extensions/machine-learning/src/common/constants.ts
  extensions/machine-learning/src/views/widgets/dashboardWidget.ts
  src/sql/azdata.proposed.d.ts
  src/sql/base/browser/ui/button/button.ts
  src/sql/base/browser/ui/infoButton/infoButton.css
  src/sql/base/browser/ui/infoButton/infoButton.ts
  src/sql/base/browser/ui/panel/media/panel.css
  src/sql/workbench/api/common/sqlExtHost.api.impl.ts
  src/sql/workbench/api/common/sqlExtHostTypes.ts
  src/sql/workbench/browser/modelComponents/button.component.ts
Labels: Port Request

#12742 [Port] Fetch arc dc config profile list from azdata #12678
  extensions/arc/package.json
  extensions/resource-deployment/src/helpers/optionSources.ts
  extensions/resource-deployment/src/interfaces.ts
  extensions/resource-deployment/src/ui/modelViewUtils.ts
Labels: Port Request

#12737 [Port] Allow non-admin BDC connections to see BDC features (#12663)
  extensions/big-data-cluster/src/bdc.d.ts
  extensions/big-data-cluster/src/bigDataCluster/controller/apiGenerated.ts
  extensions/big-data-cluster/src/bigDataCluster/controller/clusterControllerApi.ts
  extensions/big-data-cluster/src/bigDataCluster/dialog/hdfsDialogBase.ts
  extensions/mssql/src/dashboard/serviceEndpoints.ts
  extensions/mssql/src/main.ts
  extensions/mssql/src/objectExplorerNodeProvider/hdfsCommands.ts
  extensions/mssql/src/objectExplorerNodeProvider/hdfsProvider.ts
  extensions/mssql/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts
  extensions/mssql/src/objectExplorerNodeProvider/treeNodes.ts
  extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts
  extensions/mssql/src/sparkFeature/historyTask.ts
  extensions/mssql/src/sqlClusterLookUp.ts
  extensions/mssql/src/utils.ts
  extensions/notebook/src/jupyter/jupyterSessionManager.ts
  extensions/notebook/src/test/model/sessionManager.test.ts
Labels: Port Request

#12750 Fix notebook issue when creating Kusto notebooks 2nd time after launc…
  src/sql/workbench/services/notebook/browser/models/notebookModel.ts
Labels: Port Request

#12741 [Port] use selected subscriptions (#12691)
  extensions/azurecore/src/azureResource/services/subscriptionFilterService.ts
  extensions/azurecore/src/azureResource/utils.ts
  extensions/azurecore/src/azurecore.d.ts
  extensions/azurecore/src/extension.ts
  extensions/machine-learning/src/test/stubs.ts
  extensions/resource-deployment/src/localizedConstants.ts
  extensions/resource-deployment/src/ui/modelViewUtils.ts
Labels: Port Request

#12749 [Port] Improved behavior for accepting EULA. (#12453)
  extensions/azdata/src/azdata.ts
  extensions/azdata/src/extension.ts
  extensions/azdata/src/typings/azdata-ext.d.ts
  extensions/resource-deployment/src/interfaces.ts
  extensions/resource-deployment/src/localizedConstants.ts
  extensions/resource-deployment/src/services/tools/azdataTool.ts
  extensions/resource-deployment/src/services/tools/toolBase.ts
  extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts
Labels: Port Request

#12762 [Port] Fix HDFS node to only show up for BDC connections (#12714)
  extensions/mssql/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts
  extensions/mssql/src/utils.ts
Labels: Port Request

#12761 [Port] Add additional logging to spark command failures (#12706)
  extensions/mssql/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts
  extensions/mssql/src/sqlClusterLookUp.ts
Labels: Port Request

#12766 Fix search for pinned notebooks
  extensions/notebook/package.json
  extensions/notebook/src/book/bookModel.ts
  extensions/notebook/src/book/bookPinManager.ts
  extensions/notebook/src/book/bookTreeItem.ts
  extensions/notebook/src/book/bookTreeView.ts
  extensions/notebook/src/common/utils.ts
  extensions/notebook/src/extension.ts
  extensions/notebook/src/test/common/utils.test.ts
  src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookExplorerViewlet.ts
  src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookSearch.ts
Labels: Port Request

#12747 [Port] Add telemetry for ModelView wizards #12596
  extensions/notebook/src/dialog/configurePython/configurePythonWizard.ts
  extensions/resource-deployment/src/interfaces.ts
  extensions/resource-deployment/src/ui/deployClusterWizard/deployClusterWizard.ts
  extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts
  extensions/resource-deployment/src/ui/wizardBase.ts
  src/sql/azdata.proposed.d.ts
  src/sql/workbench/api/browser/mainThreadModelViewDialog.ts
  src/sql/workbench/api/common/extHostModelViewDialog.ts
  src/sql/workbench/api/common/sqlExtHost.api.impl.ts
  src/sql/workbench/api/common/sqlExtHostTypes.ts
  src/sql/workbench/browser/modal/modal.ts
  src/sql/workbench/services/dashboard/browser/newDashboardTabDialogImpl.ts
  src/sql/workbench/services/dialog/browser/customDialogService.ts
  src/sql/workbench/services/dialog/browser/dialogModal.ts
  src/sql/workbench/services/dialog/browser/wizardModal.ts
  src/sql/workbench/services/dialog/common/dialogTypes.ts
  src/sql/workbench/services/profiler/browser/profilerFilterDialog.ts
Labels: Port Request

#12778 [Port] Save username/password for BDC HDFS connections (#12667)
  extensions/mssql/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts
  extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts
  extensions/mssql/src/sqlClusterLookUp.ts
Labels: Port Request

#12784 Notebooks: WYSIWYG Add Redo, Fix Shortcuts (#12752)
  src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
Labels: Port Request

#12777 [Port] GenerateToNotebook and Deploy buttons for Notebook Wizards (#12656)
  extensions/arc/package.json
  extensions/arc/package.nls.json
  extensions/resource-deployment/src/interfaces.ts
  extensions/resource-deployment/src/localizedConstants.ts
  extensions/resource-deployment/src/services/notebookService.ts
  extensions/resource-deployment/src/services/resourceTypeService.ts
  extensions/resource-deployment/src/ui/deployClusterWizard/deployClusterWizard.ts
  extensions/resource-deployment/src/ui/deploymentInputDialog.ts
  extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts
  extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts
  extensions/resource-deployment/src/ui/wizardBase.ts
  extensions/resource-deployment/src/ui/wizardPageBase.ts
  extensions/resource-deployment/src/ui/wizardPageInfo.ts
Labels: Port Request

#12796 Aasim/release1.23/resource filter
  extensions/arc/package.json
  extensions/asde-deployment/package.json
  extensions/dacpac/src/test/testContext.ts
  extensions/machine-learning/src/test/views/utils.ts
  extensions/notebook/src/test/managePackages/managePackagesDialog.test.ts
  extensions/resource-deployment/package.json
  extensions/resource-deployment/src/constants.ts
  extensions/resource-deployment/src/interfaces.ts
  extensions/resource-deployment/src/localizedConstants.ts
  extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts
  src/sql/azdata.proposed.d.ts
  src/sql/platform/dashboard/browser/interfaces.ts
  src/sql/workbench/api/common/extHostModelView.ts
  src/sql/workbench/api/common/sqlExtHostTypes.ts
  src/sql/workbench/browser/modelComponents/listView.component.html
  src/sql/workbench/browser/modelComponents/listView.component.ts
  src/sql/workbench/browser/modelComponents/media/listView.css
  src/sql/workbench/contrib/modelView/browser/components.contribution.ts
Labels: Area - Resource Deployment, Port Request

#12803 Fix arc strings
  extensions/arc/package.nls.json
Labels: Port Request

#12813 default to relative links in images and links (#12802)
  src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
Labels: Port Request

#12827 Modify pip command in CreateJupyterBook notebook code cells (#12808)
  extensions/notebook/resources/notebooks/JupyterBooksCreate.ipynb
Labels: Port Request

#12866 Update HDFS mount path (#12865)
  extensions/big-data-cluster/src/bigDataCluster/controller/apiGenerated.ts
Labels: Port Request

#12880 Adding sql vm and sql db notebooks to october
  extensions/resource-deployment/images/azure-sql-vm.svg
  extensions/resource-deployment/notebooks/azuredb/create-sqldb.ipynb
  extensions/resource-deployment/notebooks/azurevm/create-sqlvm.ipynb
  extensions/resource-deployment/package.json
  extensions/resource-deployment/package.nls.json
  extensions/resource-deployment/src/interfaces.ts
  extensions/resource-deployment/src/services/resourceTypeService.ts
  extensions/resource-deployment/src/ui/deployAzureSQLDBWizard/constants.ts
  extensions/resource-deployment/src/ui/deployAzureSQLDBWizard/deployAzureSQLDBWizard.ts
  extensions/resource-deployment/src/ui/deployAzureSQLDBWizard/deployAzureSQLDBWizardModel.ts
  extensions/resource-deployment/src/ui/deployAzureSQLDBWizard/pages/azureSettingsPage.ts
  extensions/resource-deployment/src/ui/deployAzureSQLDBWizard/pages/basePage.ts
  extensions/resource-deployment/src/ui/deployAzureSQLDBWizard/pages/databaseSettingsPage.ts
  extensions/resource-deployment/src/ui/deployAzureSQLDBWizard/pages/summaryPage.ts
  extensions/resource-deployment/src/ui/deployAzureSQLVMWizard/constants.ts
  extensions/resource-deployment/src/ui/deployAzureSQLVMWizard/deployAzureSQLVMWizard.ts
  extensions/resource-deployment/src/ui/deployAzureSQLVMWizard/deployAzureSQLVMWizardModel.ts
  extensions/resource-deployment/src/ui/deployAzureSQLVMWizard/pages/azureSettingsPage.ts
  extensions/resource-deployment/src/ui/deployAzureSQLVMWizard/pages/basePage.ts
  extensions/resource-deployment/src/ui/deployAzureSQLVMWizard/pages/networkSettingsPage.ts
  extensions/resource-deployment/src/ui/deployAzureSQLVMWizard/pages/sqlServerSettingsPage.ts
  extensions/resource-deployment/src/ui/deployAzureSQLVMWizard/pages/summaryPage.ts
  extensions/resource-deployment/src/ui/deployAzureSQLVMWizard/pages/vmSettingsPage.ts
  extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts
Labels: Port Request

#12887 Fix connection when changing kernel from Kusto to SQL (#12881)
  src/sql/workbench/services/notebook/browser/models/notebookModel.ts
Labels: Port Request

#11880 API improvement: make registerConnectionEventProvider return disposable
  src/sql/azdata.d.ts
  src/sql/azdata.proposed.d.ts
  src/sql/workbench/api/browser/mainThreadConnectionManagement.ts
  src/sql/workbench/api/browser/mainThreadQueryEditor.ts
  src/sql/workbench/api/common/extHostConnectionManagement.ts
  src/sql/workbench/api/common/extHostQueryEditor.ts
  src/sql/workbench/api/common/sqlExtHost.api.impl.ts
  src/sql/workbench/api/common/sqlExtHost.protocol.ts
Labels: Stale PR

#12222 Connection Browse Tab
  extensions/azurecore/package.json
  extensions/azurecore/src/azureResource/tree/flatTreeProvider.ts
  extensions/azurecore/src/extension.ts
  src/sql/workbench/api/common/sqlExtHost.api.impl.ts
  src/sql/workbench/contrib/connection/browser/connection.contribution.ts
  src/sql/workbench/contrib/connection/common/connectionTreeProviderExentionPoint.ts
  src/sql/workbench/services/connection/browser/connectionBrowseTab.ts
  src/sql/workbench/services/connection/browser/connectionDialogWidget.ts
  src/sql/workbench/services/connection/browser/media/connectionBrowseTab.css
  src/sql/workbench/services/connection/common/connectionTreeService.ts
  src/sql/workbench/services/connection/test/browser/connectionDialogService.test.ts
  src/sql/workbench/services/connection/test/browser/connectionDialogWidget.test.ts
  src/sql/workbench/services/connection/test/browser/testConnectionDialogWidget.ts
  src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts
  src/sql/workbench/services/objectExplorer/common/treeNode.ts
  src/vs/workbench/api/browser/mainThreadTreeViews.ts
  src/vs/workbench/test/browser/api/mainThreadTreeViews.test.ts
Labels: Stale PR

#12907 [Port] Fix HDFS node for Integrated auth (#12906)
  extensions/mssql/src/sqlClusterLookUp.ts
Labels: Port Request
