Repository microsoft/azuredatastudio, pull requests merged in 2020-05, with the labels that each got.

#10251 Stops caching the AAD token
  src/sql/workbench/services/connection/browser/connectionManagementService.ts
Labels: Ready to Merge

#10356 Remove request promise for request-light (#10346)
  extensions/integration-tests/package.json
  extensions/mssql/package.json
  extensions/mssql/src/sparkFeature/dialog/sparkJobSubmission/sparkJobSubmissionModel.ts
  extensions/mssql/src/sparkFeature/dialog/sparkJobSubmission/sparkJobSubmissionService.ts
  extensions/mssql/yarn.lock
Labels: Port Request

#10364 [Port] Enabling Script as Create for SqlOnDemand (#10362)
  src/sql/workbench/browser/scriptingUtils.ts
  src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts
Labels: Port Request

#10361 Uncheck unselected radio buttons in Configure Python wizard. (#10344)
  extensions/notebook/src/dialog/configurePython/configurePathPage.ts
Labels: Port Request

#9032 Alex/fixforqueryrefresh
  src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
Labels: Stale PR

#9750 Keybinding for Show SQL Pane
  src/sql/workbench/contrib/editData/browser/editData.contribution.ts
  src/sql/workbench/contrib/editData/browser/editDataEditor.ts
  src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
Labels: Stale PR

#10408 port the fix for issue 10397
  extensions/mssql/package.json
  src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerWidget.component.ts
Labels: Port Request

#10399 set context (#10391)
  src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.component.ts
Labels: Port Request

#10418 Port fix for 10409 to release branch
  src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerWidget.component.ts
Labels: Port Request

#10410 Port : Fix message branding VS Code -> ADS (#10407)
  src/vs/workbench/contrib/extensions/browser/extensionsActions.ts
Labels: Port Request

#10402 Remove web smoke tests (#10380)
  build/azure-pipelines/darwin/sql-product-build-darwin.yml
Labels: Port Request

#10401 ensure we can still write version infomation if we don't recompile (#…
  build/azure-pipelines/sql-product-compile.yml
Labels: Port Request

#10432 Replace the ID of the generated connection profile with the one throu…
  src/sql/platform/connection/common/connectionManagement.ts
  src/sql/workbench/services/connection/browser/connectionDialogService.ts
  src/sql/workbench/services/connection/browser/connectionManagementService.ts
Labels: Port Request

#10433 Turn-off file extension recommendations (#10431)
  src/vs/workbench/contrib/extensions/browser/fileBasedRecommendations.ts
Labels: Port Request

#10436 Port: clear buffer when a batch is completed (#10382)
  src/sql/workbench/api/common/extHostDataProtocol.ts
Labels: Port Request

#10437 Port: Properly initialize scenario recommendations (#10434)
  src/vs/workbench/contrib/extensions/browser/extensionRecommendationsService.ts
Labels: Port Request

#10441 Notebook model ready sooner (#10420)
  src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
  src/sql/workbench/contrib/notebook/browser/notebook.component.ts
Labels: Port Request

#10460 Fix link styling for text components (#10449)
  src/sql/workbench/browser/modelComponents/text.component.ts
Labels: Port Request

#10444 Port Request : Remove config update (#10440)
  extensions/azurecore/src/azureResource/services/subscriptionFilterService.ts
Labels: Port Request

#10452 modify git edits to make webpack not be stupid (#10442)
  extensions/git/src/main.ts
Labels: Port Request

#10454 fix explorer widget dark theme
  src/sql/workbench/contrib/dashboard/browser/widgets/explorer/media/explorerWidget.css
Labels: Port Request

#10475 Port: Fix extension manager single-click (#10473)
  src/vs/platform/list/browser/listService.ts
Labels: Port Request

#10472 Port Request : Fix sql language colorization
  extensions/sql/syntaxes/sql.tmLanguage.json
Labels: Port Request

#10481 Fixes the DE icons (#10478)
  src/sql/workbench/browser/parts/views/treeView.ts
Labels: Port Request

#10498 vbump (#10423)
  product.json
Labels: Port Request

#10497 open viewlet on showPreview (#10474)
  extensions/notebook/src/book/bookTreeView.ts
Labels: Port Request

#10502 set ignoreOverrides false for ipynb and sql files (#10499)
  src/vs/workbench/api/browser/mainThreadEditors.ts
Labels: Port Request

#10512 Port: fix styles to apply to error message correctly (#10505)
  src/sql/workbench/contrib/query/browser/messagePanel.ts
Labels: Port Request

#10559 fix horizontal scroll bug (#10554)
  src/sql/workbench/contrib/query/browser/messagePanel.ts
Labels: Port Request

#10562 Revert "Query Runner Tests (#10252)"
  src/sql/platform/connection/common/connectionManagement.ts
  src/sql/workbench/common/editor/query/queryEditorInput.ts
  src/sql/workbench/contrib/charts/browser/chartView.ts
  src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
  src/sql/workbench/contrib/query/browser/gridPanel.ts
  src/sql/workbench/contrib/query/browser/messagePanel.ts
  src/sql/workbench/contrib/query/browser/queryActions.ts
  src/sql/workbench/contrib/query/browser/queryEditor.ts
  src/sql/workbench/contrib/query/test/browser/queryActions.test.ts
  src/sql/workbench/services/connection/test/browser/connectionManagementService.test.ts
  src/sql/workbench/services/editData/common/editQueryRunner.ts
  src/sql/workbench/services/insights/browser/insightsDialogController.ts
  src/sql/workbench/services/insights/test/browser/insightsDialogController.test.ts
  src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts
  src/sql/workbench/services/query/common/gridDataProvider.ts
  src/sql/workbench/services/query/common/query.ts
  src/sql/workbench/services/query/common/queryManagement.ts
  src/sql/workbench/services/query/common/queryModel.ts
  src/sql/workbench/services/query/common/queryModelService.ts
  src/sql/workbench/services/query/common/queryRunner.ts
  src/sql/workbench/services/query/test/common/queryRunner.test.ts
  src/sql/workbench/services/query/test/common/testQueryManagementService.ts
  src/sql/workbench/services/query/test/common/testQueryModelService.ts
  src/sql/workbench/services/queryHistory/common/queryHistoryServiceImpl.ts
  src/sql/workbench/test/workbenchTestServices.ts
Labels: Port Request

#10535 Open in azure portal
  extensions/azurecore/package.json
  extensions/azurecore/package.nls.json
  extensions/azurecore/src/account-provider/interfaces.ts
  extensions/azurecore/src/account-provider/providerSettings.ts
  extensions/azurecore/src/azureResource/azure-resource.d.ts
  extensions/azurecore/src/azureResource/commands.ts
  extensions/azurecore/src/azureResource/providers/database/databaseService.ts
  extensions/azurecore/src/azureResource/providers/database/databaseTreeDataProvider.ts
  extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerService.ts
  extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerTreeDataProvider.ts
  extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerService.ts
  extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerTreeDataProvider.ts
  extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerService.ts
  extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerTreeDataProvider.ts
  extensions/azurecore/src/azureResource/providers/resourceTreeDataProviderBase.ts
  extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceService.ts
  extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceTreeDataProvider.ts
  extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcService.ts
  extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcTreeDataProvider.ts
  extensions/azurecore/src/test/azureResource/providers/database/databaseTreeDataProvider.test.ts
  extensions/azurecore/src/test/azureResource/providers/databaseServer/databaseServerTreeDataProvider.test.ts
  extensions/azurecore/src/test/azureResource/resourceService.test.ts
  extensions/azurecore/src/test/azureResource/resourceTreeNode.test.ts
  src/sql/azdata.d.ts
  src/sql/azdata.proposed.d.ts
  src/sql/workbench/contrib/azure/browser/azure.contribution.ts
  src/sql/workbench/services/objectExplorer/browser/mssqlNodeContext.ts
  src/vs/workbench/workbench.common.main.ts
Labels: Ready to Merge
