Repository microsoft/azuredatastudio, pull requests merged in 2020-08, with the labels that each got.

#11457 Notebook cell toolbar additions - move cell, convert cell
  src/sql/media/icons/common-icons.css
  src/sql/workbench/contrib/notebook/browser/cellToolbarActions.ts
  src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts
  src/sql/workbench/contrib/notebook/browser/notebook.component.ts
  src/sql/workbench/contrib/notebook/test/browser/cellToolbarActions.test.ts
  src/sql/workbench/contrib/notebook/test/stubs.ts
  src/sql/workbench/services/notebook/browser/models/cell.ts
  src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts
  src/sql/workbench/services/notebook/browser/models/notebookModel.ts
Labels: Area - Notebooks

#11539 Tenant list UI for Firewall Rules
  src/sql/platform/accounts/common/accountPickerViewModel.ts
  src/sql/platform/accounts/common/firewallRuleViewModel.ts
  src/sql/workbench/services/accountManagement/browser/accountDialog.ts
  src/sql/workbench/services/accountManagement/browser/accountListRenderer.ts
  src/sql/workbench/services/accountManagement/browser/accountPicker.ts
  src/sql/workbench/services/accountManagement/browser/accountPickerImpl.ts
  src/sql/workbench/services/accountManagement/browser/accountPickerService.ts
  src/sql/workbench/services/accountManagement/browser/media/accountListRenderer.css
  src/sql/workbench/services/accountManagement/browser/media/accountPicker.css
  src/sql/workbench/services/accountManagement/browser/tenantListRenderer.ts
  src/sql/workbench/services/accountManagement/test/browser/accountPickerService.test.ts
  src/sql/workbench/services/resourceProvider/browser/firewallRuleDialog.ts
  src/sql/workbench/services/resourceProvider/browser/firewallRuleDialogController.ts
  src/sql/workbench/services/resourceProvider/browser/media/firewallRuleDialog.css
  src/sql/workbench/services/resourceProvider/test/browser/firewallRuleDialogController.test.ts
Labels: Ready to Merge

#11629 remove old code (#11620)
  extensions/notebook/package.json
Labels: Port Request

#11378 fixes duplicate list items on welcome #11366 #11578
  src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
Labels: Bug

#11643 Replace URL and use vscode.URI on local paths (#11624)
  extensions/notebook/src/book/githubRemoteBook.ts
  extensions/notebook/src/book/remoteBook.ts
  extensions/notebook/src/book/remoteBookController.ts
  extensions/notebook/src/book/sharedRemoteBook.ts
  extensions/notebook/src/dialog/remoteBookDialog.ts
  extensions/notebook/src/test/book/remoteBookController.test.ts
Labels: Port Request

#11649 Use a regex to detect notebook started message. (#11642)
  extensions/notebook/src/jupyter/serverInstance.ts
Labels: Port Request

#11658 fixes button font color not showing on welcome page #11598
  src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
Labels: Impact: UI

#11672 fixes duplicate list items on welcome #11366
  src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
Labels: Port Request

#11668 fixes open button copy not showing #11598
  src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
Labels: Port Request

#11661 Dropdown fix (#11660)
  src/sql/workbench/services/accountManagement/browser/accountPickerImpl.ts
Labels: Port Request

#11664 Return cancelled, not undefined for azure login (#11656)
  extensions/azurecore/src/account-provider/auths/azureAuth.ts
  extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts
  extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts
  extensions/azurecore/src/account-provider/azureAccountProvider.ts
  extensions/azurecore/src/account-provider/interfaces.ts
Labels: Port Request

#11680 Fix/save defaults to txt (#11623)
  src/vs/workbench/services/textfile/browser/textFileService.ts
Labels: Port Request

#11679 Revert "Do ModelView initialization actions before others (#11512)"
  src/sql/platform/dashboard/browser/interfaces.ts
  src/sql/workbench/browser/modelComponents/modelStore.ts
  src/sql/workbench/browser/modelComponents/viewBase.ts
Labels: Port Request

#11688 Add task for downloading Python package when building ADS for SAW devices. (#11659)
  build/azure-pipelines/win32/sql-product-build-win32.yml
Labels: Port Request

#11694 distro
  package.json
Labels: Port Request

#11695 distro
  package.json
Labels: Port Request

#11696 distro
  package.json
Labels: Port Request

#11698 distro
  package.json
Labels: Port Request

#11699 distro
  package.json
Labels: Port Request

#11723 Port : Fix/markdown links (#11708)
  extensions/markdown-language-features/src/commands/openDocumentLink.ts
Labels: Port Request

#11738 Defect/build break
  test/smoke/src/sql/areas/queryEditor/queryEditor.test.ts
  test/smoke/src/sql/main.ts
Labels: Port Request

#11783 2728 Kusto Function Support
  src/sql/workbench/browser/scriptingUtils.ts
  src/sql/workbench/contrib/dataExplorer/browser/nodeContextUtils.ts
  src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts
  src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts
  src/sql/workbench/services/objectExplorer/browser/media/objectTypes/objecttypes.css
  src/sql/workbench/services/objectExplorer/browser/mssqlNodeContext.ts
  src/sql/workbench/services/objectExplorer/common/nodeType.ts
Labels: Area - Kusto, Impact: Kusto

#11746 bookTreeView tests
  extensions/notebook/src/book/bookTreeView.ts
  extensions/notebook/src/test/book/book.test.ts
Labels: Stale PR

#11990 3491 Kusto Function Support
  src/sql/workbench/browser/scriptingUtils.ts
  src/sql/workbench/contrib/dataExplorer/browser/nodeContextUtils.ts
  src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts
  src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts
  src/sql/workbench/services/objectExplorer/browser/media/objectTypes/objecttypes.css
  src/sql/workbench/services/objectExplorer/browser/mssqlNodeContext.ts
  src/sql/workbench/services/objectExplorer/common/nodeType.ts
Labels: Area - Kusto, Impact: Kusto
