Repository microsoft/azuredatastudio, pull requests merged in 2020-03, with the labels that each got.

#9442 Hale test
  src/sql/workbench/contrib/connection/browser/connectionStatus.ts
  src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
Labels: Area - UX

#9506 Merge from vscode 78a4c91400152c0f27ba4d363eb56d2835f9903a
  build/azure-pipelines/darwin/product-build-darwin.yml
  extensions/package.json
  extensions/yarn.lock
  src/vs/editor/contrib/suggest/media/suggest.css
  src/vs/editor/contrib/suggest/suggestWidget.ts
  src/vs/platform/electron/electron-main/electronMainService.ts
  src/vs/platform/product/common/productService.ts
  src/vs/platform/storage/node/storageIpc.ts
  src/vs/platform/telemetry/common/telemetry.ts
  src/vs/workbench/browser/parts/panel/media/panelpart.css
  src/vs/workbench/common/editor.ts
  src/vs/workbench/common/views.ts
  src/vs/workbench/contrib/bulkEdit/browser/bulkEditPreview.ts
  src/vs/workbench/contrib/bulkEdit/browser/bulkEditTree.ts
  src/vs/workbench/contrib/markers/browser/markersTreeViewer.ts
  src/vs/workbench/electron-browser/window.ts
Labels: Approved, Port Request

#9545 Remove Decompress + Replace with Other Package (#9532)
  extensions/notebook/extension.webpack.config.js
  extensions/notebook/package.json
  extensions/notebook/src/jupyter/jupyterServerInstallation.ts
  extensions/notebook/yarn.lock
Labels: Approved, Port Request

#9552 Fix text content in title (#9534)
  src/sql/workbench/common/editor/query/queryEditorInput.ts
  src/vs/workbench/browser/workbench.contribution.ts
Labels: Approved, Port Request

#9553 Query editor input titles (#9512)
  src/sql/workbench/browser/parts/editor/editorStatusModeSelect.ts
  src/sql/workbench/contrib/editorReplacement/common/editorReplacerContribution.ts
  src/sql/workbench/contrib/editorReplacement/test/browser/editorReplacerContribution.test.ts
  src/sql/workbench/contrib/query/browser/queryInputFactory.ts
  src/sql/workbench/contrib/query/test/browser/queryInputFactory.test.ts
  src/sql/workbench/services/languageAssociation/common/doHandleUpgrade.ts
  src/sql/workbench/services/languageAssociation/common/languageAssociation.ts
  src/sql/workbench/services/queryEditor/test/common/testQueryEditorService.ts
  src/sql/workbench/test/workbenchTestServices.ts
Labels: Approved, Port Request

#9514 (port) fix xml formatting (#9510)
  src/sql/workbench/contrib/query/browser/gridPanel.ts
Labels: Approved, Port Request

#9535 Fix long account dialog text hiding actions (Port #9449)
  src/sql/workbench/services/accountManagement/browser/media/accountDialog.css
  src/sql/workbench/services/accountManagement/browser/media/accountListRenderer.css
Labels: Approved, Port Request

#9559 Reverts ADS Always encrypted
  extensions/mssql/package.json
  extensions/mssql/package.nls.json
Labels: Approved, Port Request

#9568 Port #9564 - Add BDC Dashboard Refresh Icon Back In
  extensions/big-data-cluster/resources/dark/refresh_inverse.svg
  extensions/big-data-cluster/resources/light/refresh.svg
Labels: Approved, Port Request

#9574 Notebooks: Fix Internal Links on Windows (#9513)
  src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts
Labels: Approved, Port Request

#9575 Add separate dialog to notebook charts for specifying chart options. …
  src/sql/media/icons/common-icons.css
  src/sql/media/icons/settings.svg
  src/sql/media/icons/settings_inverse.svg
  src/sql/workbench/browser/modal/modal.ts
  src/sql/workbench/contrib/charts/browser/actions.ts
  src/sql/workbench/contrib/charts/browser/chartTab.ts
  src/sql/workbench/contrib/charts/browser/chartView.ts
  src/sql/workbench/contrib/charts/browser/configureChartDialog.ts
  src/sql/workbench/contrib/charts/browser/media/chartView.css
  src/sql/workbench/contrib/charts/test/browser/chartView.test.ts
  src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
  src/sql/workbench/services/objectExplorer/browser/media/objectTypes/objecttypes.css
Labels: Approved, Port Request

#9589 Merge from vscode a9b7cb4ee1caac9a9ac1467848017b4cd9765d9e
  src/vs/platform/windows/electron-main/windowsMainService.ts
Labels: Approved, Port Request

#9561 ok button target fix
  extensions/azurecore/src/azureResource/commands.ts
  extensions/azurecore/src/azureResource/services/subscriptionFilterService.ts
  src/vs/vscode.d.ts
  src/vs/workbench/api/common/extHostQuickOpen.ts
Labels: Approved, Port Request

#9600 check for len > 1 (#9586)
  extensions/notebook/resources/notebooks/JupyterBooksCreate.ipynb
Labels: Approved, Port Request

#9598 Fix find highlight for multiple find occurrences (#9518)
  src/sql/workbench/contrib/notebook/find/notebookFindModel.ts
  src/sql/workbench/contrib/notebook/test/electron-browser/notebookFindModel.test.ts
Labels: Approved, Port Request

#9601 Fix search icon only working when section expanded (#9596)
  extensions/notebook/src/book/bookTreeItem.ts
Labels: Approved, Port Request

#9599 vbump for tsg book (#9567)
  build/builtInExtensions.json
Labels: Approved, Port Request

#9590 Hook up the command again (#9587)
  extensions/azurecore/src/account-provider/azureAccountProvider2.ts
  extensions/azurecore/src/account-provider/azureAccountProviderService.ts
  src/sql/azdata.d.ts
  src/sql/platform/accounts/test/common/testAccountManagementService.ts
  src/sql/workbench/api/browser/mainThreadAccountManagement.ts
  src/sql/workbench/api/common/sqlExtHost.protocol.ts
Labels: Approved, Port Request

#9607 Merge from vscode b7235954cf5c8ec4086a44262d38265552272a7a
  src/vs/platform/opener/browser/link.ts
  src/vs/workbench/browser/parts/notifications/notificationsViewer.ts
Labels: Approved, Port Request

#9594 change usage of view container (#9591)
  src/sql/workbench/contrib/dataExplorer/browser/dataExplorer.contribution.ts
  src/sql/workbench/contrib/dataExplorer/browser/dataExplorerViewlet.ts
Labels: Approved, Port Request

#9626 fixed opening book on win (#9622)
  extensions/notebook/package.nls.json
  extensions/notebook/resources/notebooks/JupyterBooksCreate.ipynb
Labels: Approved, Port Request

#9620 Add device code authentication (#9097)
  extensions/azurecore/package.json
  extensions/azurecore/package.nls.json
  extensions/azurecore/src/account-provider/azureAccountProviderService.ts
Labels: Approved, Port Request

#9637 fix issue with setting false (#9611)
  src/sql/workbench/common/editor/query/gridTableState.ts
  src/sql/workbench/common/editor/query/queryResultsInput.ts
  src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
  src/sql/workbench/contrib/query/browser/actions.ts
  src/sql/workbench/contrib/query/browser/gridPanel.ts
  src/sql/workbench/contrib/query/browser/queryResultsView.ts
  src/sql/workbench/test/common/editor/query/gridTableState.test.ts
Labels: Approved, Port Request

#9531 Bump extensions for release
  extensionsGallery-insider.json
  extensionsGallery.json
Labels: Stale PR

#9688 Fix handling of connections in editors (#9682)
  src/sql/workbench/browser/scriptingUtils.ts
  src/sql/workbench/browser/taskUtilities.ts
  src/sql/workbench/contrib/query/browser/queryActions.ts
  src/sql/workbench/contrib/query/browser/queryInputFactory.ts
  src/sql/workbench/contrib/tasks/common/tasksAction.ts
  src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
  src/sql/workbench/services/queryEditor/common/queryEditorService.ts
  src/sql/workbench/services/queryEditor/test/common/testQueryEditorService.ts
  src/sql/workbench/services/tasks/common/tasksService.ts
Labels: Approved, Port Request

#9694 Timeout extention for Linux and Windows pipelines (#9643)
  build/azure-pipelines/sql-product-build.yml
Labels: Approved
