Repository microsoft/azuredatastudio, pull requests merged in 2021-03, with the labels that each got.

#14457 Notebook cell and modal fix - follow up after Lucy's 14433.
  src/sql/workbench/browser/modal/modal.ts
  src/sql/workbench/contrib/notebook/browser/cellViews/codeCell.component.html
  src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.html
Labels: Area - Notebooks

#14605 [Port] Fix AKV security token issue
  extensions/mssql/src/features.ts
Labels: Port Request

#14661 Fixing welcome page tour. (#14640)
  src/sql/workbench/contrib/dataExplorer/browser/dataExplorerViewlet.ts
  src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookExplorerViewlet.ts
  src/sql/workbench/contrib/welcome/page/browser/gettingStartedTour.ts
  src/vs/workbench/browser/parts/activitybar/activitybarPart.ts
Labels: Port Request

#14636 handle query gallery with tags (#14633)
  src/vs/platform/extensionManagement/common/extensionGalleryService.ts
Labels: Port Request

#14619 [Port Request] Queue concurrent calls when initializing contents in BookModel (#14586)
  extensions/notebook/src/book/bookModel.ts
Labels: Port Request

#14679 Manage Packages icon position fix (#14528)
  src/sql/workbench/contrib/notebook/browser/notebook.component.ts
  src/vs/platform/actions/browser/menuEntryActionViewItem.ts
Labels: Port Request

#14689 [Port] Disable auto sync service (#14677)
  src/vs/platform/userDataSync/common/userDataAutoSyncService.ts
  src/vs/platform/userDataSync/test/common/userDataAutoSyncService.test.ts
  src/vs/workbench/services/userDataSync/browser/userDataAutoSyncEnablementService.ts
Labels: Port Request

#14706 [Port] Fix welcome page (#14701)
  src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
  src/sql/workbench/contrib/welcome/page/browser/welcomePage.css
  src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
  src/vs/base/browser/dom.ts
Labels: Port Request

#14711 [Port] Fix filtered resource options persisting across deployments (#14702)
  extensions/resource-deployment/src/ui/resourceTypeWizard.ts
  extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts
Labels: Port Request

#14731 Fix script loading in sandbox windows (#14727)
  src/bootstrap-window.js
  src/bootstrap.js
Labels: Port Request

#14705 Add Product Feedback survey link to welcome page
  src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
Labels: Approved

#14739 [Port] Add Product Feedback survey link to welcome page (#14705)
  src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
Labels: Port Request

#14792 [Port] Sync up latest fixes/updates to Arc extension to 1.27 branch
  extensions/arc/notebooks/arcDeployment/deploy.arc.data.controller.ipynb
  extensions/arc/notebooks/arcDeployment/deploy.sql.existing.arc.ipynb
  extensions/arc/package.json
  extensions/arc/package.nls.json
  extensions/arc/src/common/utils.ts
  extensions/arc/src/localizedConstants.ts
  extensions/arc/src/test/models/postgresModel.test.ts
  extensions/arc/src/ui/dashboards/miaa/miaaConnectionStringsPage.ts
  extensions/arc/src/ui/dashboards/miaa/miaaDashboard.ts
  extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
  extensions/arc/src/ui/dashboards/postgres/postgresDashboard.ts
  extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts
  extensions/arc/src/ui/dashboards/postgres/postgresResourceHealthPage.ts
  extensions/arc/src/ui/dashboards/postgres/postgresSupportRequestPage.ts
Labels: Port Request
