Repository microsoft/azuredatastudio, pull requests merged in 2023-09, with the labels that each got.

#24237 SQL-migration - optimize validation experience to allow retry-failed only validations and skip successful.
  extensions/sql-migration/images/redo.svg
  extensions/sql-migration/src/constants/iconPathHelper.ts
  extensions/sql-migration/src/constants/strings.ts
  extensions/sql-migration/src/dialog/validationResults/validateIrDialog.ts
Labels: Area - SQL Assessment, Area - SQL Migration

#24283 Update IR Revalidation button to accurate name
  extensions/sql-migration/src/constants/strings.ts
  extensions/sql-migration/src/dialog/validationResults/validateIrDialog.ts
Labels: Area - SQL Migration

#24326 SQL-Migration Extension Version bump-up
  extensions/sql-migration/package.json
Labels: Area - SQL Assessment, Area - SQL Migration

#24339 Revert the changes of row fileGroup table which was added accidentally
  extensions/mssql/src/objectManagement/ui/databaseDialog.ts
  extensions/mssql/src/ui/dialogBase.ts
Labels: Bug

#24383 Cherry Pick - Database properties fixes
  extensions/mssql/src/objectManagement/interfaces.ts
  extensions/mssql/src/objectManagement/localizedConstants.ts
  extensions/mssql/src/objectManagement/objectManagementService.ts
  extensions/mssql/src/objectManagement/ui/databaseDialog.ts
  extensions/mssql/src/objectManagement/ui/databaseFileDialog.ts
Labels: Port Request

#24384 More server properties fixes (#24366)
  extensions/mssql/src/objectManagement/constants.ts
  extensions/mssql/src/objectManagement/interfaces.ts
  extensions/mssql/src/objectManagement/localizedConstants.ts
  extensions/mssql/src/objectManagement/ui/serverPropertiesDialog.ts
Labels: Port Request

#24387 sts vBump 4.9.1.2 from 4.9.0.37
  extensions/mssql/config.json
Labels: Port Request

#24398 Adding new database inline icon in release (#24375)
  extensions/mssql/package.json
Labels: Port Request

#24399 handle error scenarios for validity check (#24393)
  src/sql/workbench/browser/modelComponents/componentBase.ts
Labels: Port Request

#24412 Use remote file dialog for database and server properties dialogs (#24390)
  extensions/azuremonitor/package.json
  extensions/azuremonitor/yarn.lock
  extensions/datavirtualization/package.json
  extensions/datavirtualization/yarn.lock
  extensions/import/package.json
  extensions/import/yarn.lock
  extensions/kusto/package.json
  extensions/kusto/yarn.lock
  extensions/mssql/config.json
  extensions/mssql/package.json
  extensions/mssql/src/objectManagement/ui/attachDatabaseDialog.ts
  extensions/mssql/src/objectManagement/ui/databaseDialog.ts
  extensions/mssql/src/objectManagement/ui/databaseFileDialog.ts
  extensions/mssql/src/objectManagement/ui/serverPropertiesDialog.ts
  extensions/mssql/yarn.lock
  extensions/sql-migration/package.json
  extensions/sql-migration/yarn.lock
  src/sql/azdata.proposed.d.ts
  src/sql/workbench/api/browser/mainThreadDataProtocol.ts
  src/sql/workbench/api/browser/mainThreadWindow.ts
  src/sql/workbench/api/common/extHostDataProtocol.ts
  src/sql/workbench/api/common/extHostWindow.ts
  src/sql/workbench/api/common/sqlExtHost.api.impl.ts
  src/sql/workbench/api/common/sqlExtHost.protocol.ts
  src/sql/workbench/services/fileBrowser/browser/fileBrowserDialog.ts
  src/sql/workbench/services/fileBrowser/browser/fileBrowserDialogController.ts
  src/sql/workbench/services/fileBrowser/browser/media/fileBrowserDialog.css
  src/sql/workbench/services/fileBrowser/common/fileBrowserDialogController.ts
  src/sql/workbench/services/fileBrowser/common/fileBrowserService.ts
  src/sql/workbench/services/fileBrowser/common/fileBrowserViewModel.ts
  src/sql/workbench/services/fileBrowser/common/interfaces.ts
Labels: Port Request

#24416 enable server and db properties (#24406)
  extensions/mssql/package.json
Labels: Port Request

#24407 max file size input field has wierd enable/disable behavior #24322
  extensions/mssql/src/objectManagement/ui/databaseFileDialog.ts
Labels: Bug, Approved

#24428 max file size input field has wierd enable/disable behavior #24322 (#…
  extensions/mssql/src/objectManagement/ui/databaseFileDialog.ts
Labels: Port Request

#24430 [Release/1.46] Prompt to refresh account on error AADSTS700082 (#24423)
  extensions/azurecore/src/account-provider/auths/azureAuth.ts
  extensions/azurecore/src/constants.ts
Labels: Port Request

#24433 [Release/1.46] Fix Edit Data Revert for New Row.
  src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
Labels: Area - Edit Data, Port Request

#24434 [Release/1.46] Pin ipykernel package to v5.5.5
  extensions/notebook/src/jupyter/jupyterServerInstallation.ts
  extensions/notebook/src/test/python/jupyterInstallation.test.ts
Labels: Port Request

#24446 Filegroup Memory optimized table Add button should be disabled when have at least one filegroup
  extensions/mssql/src/objectManagement/ui/databaseDialog.ts
  extensions/mssql/src/ui/dialogBase.ts
Labels: Bug, Area - Basic Admin

#24449 [Release/1.46] Pin traitlets package to v5.9.0
  extensions/notebook/src/jupyter/jupyterServerInstallation.ts
  extensions/notebook/src/test/python/jupyterInstallation.test.ts
Labels: Port Request

#24450 [Port Request] Fix enable/disable script button behavior
  extensions/mssql/src/ui/scriptableDialogBase.ts
Labels: Port Request

#24452 Filegroup Memory optimized Add button should be disabled when have on…
  extensions/mssql/src/objectManagement/ui/databaseDialog.ts
  extensions/mssql/src/ui/dialogBase.ts
Labels: Bug, Port Request

#24286 Added Arialabel for SqlMigration Service Name InputBox
  extensions/sql-migration/src/dialog/createSqlMigrationService/createSqlMigrationServiceDialog.ts
Labels: Impact: Accessibility

#24465 Azure SQL MI supports maximum 100 DB per instance.
  extensions/sql-migration/src/constants/strings.ts
  extensions/sql-migration/src/dialog/assessment/sqlDatabasesTree.ts
Labels: Area - SQL Assessment, Area - SQL Migration

#24528 Ramudaykumar/vbump sql migration 1.4.10 insiders
  extensionsGallery-insider.json
Labels: Area - SQL Migration
