Repository microsoft/azuredatastudio, pull requests merged in 2023-07, with the labels that each got.

#23746 [Loc] added translated getting started to langpack (#23744)
  i18n/ads-language-pack-de/translations/main.i18n.json
  i18n/ads-language-pack-es/translations/main.i18n.json
  i18n/ads-language-pack-fr/translations/main.i18n.json
  i18n/ads-language-pack-it/translations/main.i18n.json
  i18n/ads-language-pack-ja/translations/main.i18n.json
  i18n/ads-language-pack-ko/translations/main.i18n.json
  i18n/ads-language-pack-pt-BR/translations/main.i18n.json
  i18n/ads-language-pack-ru/translations/main.i18n.json
  i18n/ads-language-pack-zh-hans/translations/main.i18n.json
  i18n/ads-language-pack-zh-hant/translations/main.i18n.json
  resources/xlf/de/sql.de.xlf
  resources/xlf/es/sql.es.xlf
  resources/xlf/fr/sql.fr.xlf
  resources/xlf/it/sql.it.xlf
  resources/xlf/ja/sql.ja.xlf
  resources/xlf/ko/sql.ko.xlf
  resources/xlf/pt-br/sql.pt-BR.xlf
  resources/xlf/ru/sql.ru.xlf
  resources/xlf/zh-hans/sql.zh-Hans.xlf
  resources/xlf/zh-hant/sql.zh-Hant.xlf
Labels: Area - Localization, Port Request

#23772 [Port] Fix dropdown behavior (#23708)
  src/sql/base/browser/ui/dropdownList/dropdownList.ts
Labels: Port Request

#23774 Create new context menu item for Database (#23771)
  extensions/mssql/package.json
  extensions/mssql/package.nls.json
  extensions/mssql/src/objectManagement/commands.ts
Labels: Port Request

#23773 Limit Detach Database and Database/Server Properties to insiders and dev builds.
  extensions/mssql/package.json
Labels: Port Request

#23781 [Port] Fix flaky ADS unit tests by using DOM rendering (#23770)
  src/vs/platform/configuration/test/common/testConfigurationService.ts
  src/vs/workbench/contrib/experiments/test/electron-sandbox/experimentService.test.ts
  src/vs/workbench/contrib/terminalContrib/accessibility/test/browser/bufferContentTracker.test.ts
  src/vs/workbench/contrib/terminalContrib/links/test/browser/terminalLinkManager.test.ts
  src/vs/workbench/contrib/welcomeGettingStarted/test/browser/gettingStartedMarkdownRenderer.test.ts
  src/vs/workbench/services/configuration/test/browser/configuration.test.ts
  src/vs/workbench/services/configuration/test/browser/configurationEditing.test.ts
  src/vs/workbench/services/configuration/test/browser/configurationService.test.ts
  src/vs/workbench/services/configurationResolver/test/electron-sandbox/configurationResolverService.test.ts
  src/vs/workbench/services/editor/test/browser/editorResolverService.test.ts
  src/vs/workbench/services/extensionManagement/test/browser/extensionEnablementService.test.ts
  src/vs/workbench/services/extensions/test/browser/extensionService.test.ts
  src/vs/workbench/services/history/test/browser/historyService.test.ts
Labels: Port Request

#23778 [Port] Update vscode version for Profiler extension
  extensions/profiler/package.json
Labels: Port Request

#23775 [Release/1.45] Fix connection URI default value comparisons
  extensions/mssql/config.json
  src/sql/platform/connection/common/connectionConfig.ts
  src/sql/platform/connection/common/connectionProfile.ts
  src/sql/platform/connection/common/providerConnectionInfo.ts
  src/sql/platform/connection/test/common/connectionConfig.test.ts
Labels: Port Request

#23789 Recovery time In seconds validation
  extensions/mssql/src/objectManagement/ui/databaseDialog.ts
Labels: Area - Basic Admin

#23791 Fixing unsupported providers behavior on Async Server Tree (#23758)
  src/sql/workbench/services/connection/browser/connectionManagementService.ts
  src/sql/workbench/services/objectExplorer/browser/treeSelectionHandler.ts
Labels: Port Request

#23804 Making IsLedger Property to Read-only
  extensions/mssql/src/objectManagement/ui/databaseDialog.ts
Labels: Area - Basic Admin

#23838 Update telemetry opt out URL (#23835)
  product.json
Labels: Port Request

#23850 [Port] Fix dialog buttons (#23843)
  src/sql/workbench/services/dialog/browser/dialogModal.ts
  src/sql/workbench/services/dialog/browser/wizardModal.ts
  src/tsec.exemptions.json
Labels: Port Request

#23844 Update SQL Tools version to 4.8.1.3
  extensions/mssql/config.json
Labels: Port Request

#23851 Fixing chartjs scale values in release
  src/sql/workbench/contrib/charts/browser/graphInsight.ts
Labels: Port Request

#23853 Fixing azdata connect command not adding connection to OE in release.
  src/sql/workbench/contrib/connection/browser/connection.contribution.ts
Labels: Port Request

#23852 [Port] update ITreeElement with ICompressedTreeElement (#23839)
  src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookSearch.ts
Labels: Port Request

#23869 [Port] Fix file browser opening race condition
  src/sql/workbench/services/fileBrowser/browser/fileBrowserDialog.ts
Labels: Port Request

#23871 [Port] Fix error when opening create project from db dialog without connection
  extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
Labels: Port Request

#23874 [Port] Fix Notebook toolbar and cell toolbar dropdown alignment
  src/sql/workbench/contrib/notebook/browser/cellToolbarActions.ts
  src/sql/workbench/contrib/notebook/browser/notebook.component.ts
Labels: Port Request

#23876 [Port] Add limit on the file size that can be opened with Open XEL feature
  src/sql/workbench/contrib/profiler/browser/profilerActions.contribution.ts
  src/sql/workbench/services/profiler/browser/interfaces.ts
  src/sql/workbench/services/profiler/browser/profilerService.ts
Labels: Port Request

#23881 [Port Request] Add basic validation to database names (#23842)
  extensions/mssql/src/objectManagement/ui/databaseDialog.ts
  extensions/mssql/src/ui/dialogBase.ts
Labels: Port Request

#23882 Better fix for file browser race condition
  src/sql/workbench/services/fileBrowser/browser/fileBrowserDialog.ts
Labels: Port Request

#23891 [Release/1.45] Fix serverInfo undefined due to wrong connection URI set on connection
  src/sql/workbench/services/connection/browser/connectionManagementService.ts
Labels: Port Request

#23903 [Release/1.45] Clean encryption keys with cache clear command (#23875)
  extensions/azurecore/src/account-provider/auths/azureAuth.ts
  extensions/azurecore/src/account-provider/azureAccountProviderService.ts
  extensions/azurecore/src/account-provider/utils/fileEncryptionHelper.ts
  extensions/azurecore/src/account-provider/utils/msalCachePlugin.ts
  extensions/azurecore/src/extension.ts
  extensions/azurecore/src/localizedConstants.ts
  extensions/azurecore/src/utils.ts
Labels: Port Request

#23928 [Release/1.45] Allow empty username + fix profiles on read (#23924)
  extensions/mssql/config.json
  src/sql/platform/connection/common/connectionConfig.ts
  src/sql/platform/connection/common/connectionProfile.ts
Labels: Port Request

#23916 Port request for connection title removal
  extensions/mssql/src/tableDesigner/tableDesigner.ts
  src/sql/azdata.proposed.d.ts
  src/sql/platform/connection/common/connectionManagement.ts
  src/sql/platform/connection/common/connectionStore.ts
  src/sql/platform/connection/common/providerConnectionInfo.ts
  src/sql/platform/connection/test/common/testConnectionManagementService.ts
  src/sql/workbench/api/browser/mainThreadConnectionManagement.ts
  src/sql/workbench/api/common/extHostConnectionManagement.ts
  src/sql/workbench/api/common/sqlExtHost.api.impl.ts
  src/sql/workbench/api/common/sqlExtHost.protocol.ts
  src/sql/workbench/browser/editor/profiler/dashboardInput.ts
  src/sql/workbench/common/editor/query/queryEditorInput.ts
  src/sql/workbench/contrib/connection/browser/connectionStatus.ts
  src/sql/workbench/contrib/dashboard/browser/services/breadcrumb.service.ts
  src/sql/workbench/contrib/notebook/browser/notebookActions.ts
  src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
  src/sql/workbench/services/bootstrap/browser/commonServiceInterface.service.ts
  src/sql/workbench/services/connection/browser/connectionBrowseTab.ts
  src/sql/workbench/services/connection/browser/connectionManagementService.ts
  src/sql/workbench/services/connection/test/browser/connectionManagementService.test.ts
  src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts
  src/sql/workbench/services/objectExplorer/browser/serverTreeRenderer.ts
  src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts
  src/sql/workbench/services/objectExplorer/test/browser/treeUpdateUtils.test.ts
Labels: Port Request

#23929 Update .cachesalt
  build/.cachesalt
Labels: Port Request

#23936 Fix connection drag and drop in release.
  src/sql/workbench/services/connection/browser/connectionManagementService.ts
Labels: Port Request

#23937 Removing unnecessary tree expansions causing errors to popup again (#…
  src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
  src/sql/workbench/services/objectExplorer/browser/asyncServerTree.ts
Labels: Port Request

#23950 [Release/1.45] Fix context menu in treeViews (#23948)
  src/sql/workbench/contrib/views/browser/treeView.ts
Labels: Port Request

#23967 [Port] Temporary fix for Data Explorer context menus (#23957)
  src/sql/workbench/contrib/views/browser/treeView.ts
Labels: Port Request

#23990 Erpett/changelog port1.45
  CHANGELOG.md
Labels: Port Request

#24022 [Port] Update vs code engine version to 1.79.2 (#24020)
  product.json
Labels: Port Request

#24024 Commenting out listener threshold to fix extensions having mem leaks
  src/vs/base/common/event.ts
Labels: Port Request

#24033 (July Hotfix Port Request) Fix for query editor entry in recent connections
  src/sql/workbench/services/connection/browser/connectionDialogService.ts
Labels: Port Request

#24032 (July hotfix port) Update session dropdown and fix running state info
  src/sql/workbench/contrib/profiler/browser/profilerEditor.ts
  src/sql/workbench/services/profiler/browser/profilerService.ts
Labels: Port Request
