Repository microsoft/azuredatastudio, pull requests merged in 2023-10, with the labels that each got.

#24555 Bump Electron to 22.3.15 (#24554)
  .yarnrc
  package.json
  test/smoke/src/sql/main.ts
  yarn.lock
Labels: Port Request

#24536 Adding fiilegroup name label to the input box and auto focus of newly added row
  extensions/mssql/src/objectManagement/localizedConstants.ts
  extensions/mssql/src/objectManagement/ui/databaseDialog.ts
Labels: Area - Basic Admin

#24558 [Port] Delete compilation.tar.gz after it's been extracted (#24539)
  build/azure-pipelines/linux/sql-product-build-linux.yml
Labels: Port Request

#24560 Database Properties: Database Scoped Configuration Table Has Unnecessary Double Scrollbars
  extensions/mssql/src/objectManagement/ui/databaseDialog.ts
Labels: Area - Basic Admin

#24556 Premium SSD v2 disks in SQL VM recommendations
  extensions/sql-migration/config.json
  extensions/sql-migration/package.json
  extensions/sql-migration/src/constants/strings.ts
  extensions/sql-migration/src/dialog/skuRecommendationResults/skuRecommendationResultsDialog.ts
  extensions/sql-migration/src/service/contracts.ts
  extensions/sql-migration/src/service/features.ts
  extensions/sql-migration/src/wizard/skuRecommendationPage.ts
Labels: Area - SQL Assessment, Area - SQL Migration

#24580 vbump sql migration 1.4.10 in extension gallery
  extensionsGallery.json
Labels: Area - SQL Migration

#24573 Fix to Disable Apply button for Query Store tab when no changes are made
  extensions/mssql/src/objectManagement/ui/databaseDialog.ts
Labels: Area - Basic Admin

#24653 Improves "save as Excel" functionality
  src/sql/azdata.proposed.d.ts
  src/sql/platform/query/common/query.ts
  src/sql/workbench/contrib/query/browser/query.contribution.ts
  src/sql/workbench/services/query/common/resultSerializer.ts
Labels: Enhancement

#24764 Adjusting DSC table height
  extensions/mssql/src/objectManagement/ui/databaseDialog.ts
Labels: Task

#24666 filestream table should be disabled when server filestream access level is disableda and DSC table height adjusted
  extensions/mssql/src/objectManagement/interfaces.ts
  extensions/mssql/src/objectManagement/ui/databaseDialog.ts
Labels: Area - Basic Admin

#24765 creating get backup folder request to fetch the sql server default ba…
  extensions/mssql/src/contracts.ts
  extensions/mssql/src/mssql.d.ts
  extensions/mssql/src/objectManagement/objectManagementService.ts
Labels: Area - Basic Admin
