Repository microsoft/azuredatastudio, pull requests merged in 2024-02, with the labels that each got.

#25300 vBump ScriptDom version for sql projects
  extensions/sql-database-projects/src/tools/buildHelper.ts
Labels: Bug

#25359 Add write permissions to PR labelling action (#25356)
  .github/workflows/on-pr-open.yml
Labels: Port Request

#25357 Porting STS version update to release branch 1.48
  extensions/mssql/config.json
Labels: Port Request

#25381 Porting sql-database-project extension version to 1.4.2
  extensions/sql-database-projects/package.json
Labels: Port Request

#25384 [Port] Fix custom options selection event (#25380)
  src/sql/workbench/services/connection/browser/connectionWidget.ts
Labels: Port Request

#25385 Fix arguments for openNotebookFolder command registration (#25374)
  extensions/notebook/src/book/bookTocManager.ts
  extensions/notebook/src/book/githubRemoteBook.ts
  extensions/notebook/src/extension.ts
Labels: Port Request

#25396 STS vBump to 4.11.1.1
  extensions/mssql/config.json
Labels: Port Request

#25400 [Port] Remove inline commands for dropping objects (#25399)
  extensions/mssql/package.json
Labels: Port Request

#25411 Port Request for Langpack Fix 2-26-2024
  i18n/ads-language-pack-de/package.json
  i18n/ads-language-pack-es/package.json
  i18n/ads-language-pack-es/translations/extensions/Microsoft.sql-migration.i18n.json
  i18n/ads-language-pack-fr/package.json
  i18n/ads-language-pack-fr/translations/extensions/Microsoft.sql-migration.i18n.json
  i18n/ads-language-pack-it/package.json
  i18n/ads-language-pack-it/translations/extensions/Microsoft.sql-migration.i18n.json
  i18n/ads-language-pack-ja/package.json
  i18n/ads-language-pack-ja/translations/extensions/Microsoft.sql-migration.i18n.json
  i18n/ads-language-pack-ko/package.json
  i18n/ads-language-pack-ko/translations/extensions/Microsoft.azurecore.i18n.json
  i18n/ads-language-pack-ko/translations/extensions/Microsoft.cms.i18n.json
  i18n/ads-language-pack-ko/translations/extensions/Microsoft.kusto.i18n.json
  i18n/ads-language-pack-ko/translations/extensions/Microsoft.mssql.i18n.json
  i18n/ads-language-pack-ko/translations/extensions/Microsoft.notebook.i18n.json
  i18n/ads-language-pack-ko/translations/extensions/Microsoft.sql-migration.i18n.json
  i18n/ads-language-pack-ko/translations/main.i18n.json
  i18n/ads-language-pack-pt-BR/package.json
  i18n/ads-language-pack-pt-BR/translations/extensions/Microsoft.sql-migration.i18n.json
  i18n/ads-language-pack-ru/package.json
  i18n/ads-language-pack-zh-hans/package.json
  i18n/ads-language-pack-zh-hant/package.json
  i18n/ads-language-pack-zh-hant/translations/extensions/Microsoft.sql-migration.i18n.json
  resources/xlf/es/Microsoft.sql-migration.es.xlf
  resources/xlf/fr/Microsoft.sql-migration.fr.xlf
  resources/xlf/it/Microsoft.sql-migration.it.xlf
  resources/xlf/ja/Microsoft.sql-migration.ja.xlf
  resources/xlf/ko/Microsoft.azurecore.ko.xlf
  resources/xlf/ko/Microsoft.cms.ko.xlf
  resources/xlf/ko/Microsoft.kusto.ko.xlf
  resources/xlf/ko/Microsoft.mssql.ko.xlf
  resources/xlf/ko/Microsoft.notebook.ko.xlf
  resources/xlf/ko/Microsoft.sql-migration.ko.xlf
  resources/xlf/ko/sql.ko.xlf
  resources/xlf/pt-br/Microsoft.sql-migration.pt-BR.xlf
  resources/xlf/zh-hant/Microsoft.sql-migration.zh-Hant.xlf
Labels: Area - Localization, Port Request
